### ISSUE TITLE
Investigate error in clean_data.py, check en-US

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#794]
```
gandi ~/transvision((v5.0)) $ ./app/scripts/clean_data.py --delete
--
Analyzing sources in config/sources
l20n_test.txt is not a supported repository.
Removing file: /srv/mozfr01-data/home/pascalc/transvision/app/config/sources/l20n_test.txt
gaia_versions.txt is not a supported repository.
Removing file: /srv/mozfr01-data/home/pascalc/transvision/app/config/sources/gaia_versions.txt
--
Analyzing folders in supported repositories
--
Analyze central
--
Analyze gaia_2_5
Traceback (most recent call last):
  File "./app/scripts/clean_data.py", line 149, in <module>
    main()
  File "./app/scripts/clean_data.py", line 112, in main
    available_folders = os.walk(folder_path).next()[1]
StopIteration
```

I think this is due to sources and code being in a mixed state (no more gaia in code, gaia sources still around).

Also need to double check if we remove en-US (I have the feeling we don't).

**Comment by flodolo** [comment]
Managed to reproduce the error with Gaia repositories defined in `config/sources` but no folder for the repos (since setup.sh doesn't create them anymore).
